# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efe241a14911873c19f6881a1b753a45e46109f969245f241d5092fc1f011d6bdca2a201493c5cd2b37d97e1094b8d70c63c12088c35872874a7ee612fe90acc

test:
  secret_key_base: 53d21f0d7d91cf79bd7f05d5f8ce72e830853904a8874e3c0a8b29e7c8de9e3edc449a3e4afb740ac7c002c2ed9949bc84f0dd3c2a27c320936466bf5af06b64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
